apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: test-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

  # kubectl auth can-i get pod --as system:serviceaccount:default:test-sa --namespace default
  # kubectl auth can-i create pod --as system:serviceaccount:default:test-sa --namespace default