apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  FIRST_NAME: "KubeFromMapFirstName"
  SECOND_NAME: "KubeFromMapSecondName"
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: app:1.0.0
      env:
        - name: APP_NAME
          value: Kubernetes
        - name: MY_NAME
          value: Przemek
        - name: FIRST_NAME_APP
          valueFrom:
            configMapKeyRef:
              name: config
              key: FIRST_NAME
      envFrom:
        - configMapRef:
            name: config
