# helm dep update
# helm template --namespace podinfo --create-namespace podinfo . > _template.yaml
# helm upgrade --install --namespace podinfo --create-namespace podinfo .
podinfo:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: podinfo.34.118.54.27.nip.io
        paths:
          - path: /
            pathType: ImplementationSpecific


# https://cert-manager.io/docs/tutorials/acme/nginx-ingress/
