apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: app-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
  annotations:
    kubernetes.io/change-cause: "image update to version X"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: app
          image: app:1.0.0
          livenessProbe:
            httpGet:
              port: 5000
              path: "/health/liveness"
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              port: 5000
              path: "/health/readiness"
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          ports:
            - containerPort: 5000
              name: http
