wordpressUsername: admin
wordpressPassword: password
mariadb:
  auth:
    rootPassword: secretpassword

wordpressBlogName: Kurs Kubernetesa!
memcached:
  enabled: true

service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: wordpress.127.0.0.1.nip.io
  # mkcert --key-file key.pem --cert-file cert.pem wordpress.127.0.0.1.nip.io
  # k create secret tls blog-tls --key key.pem --cert cert.pem
  tls: true
  extraTls:
    - hosts:
      - wordpress.127.0.0.1.nip.io
      secretName: blog-tls