apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox:1.28
      command: [ 'sh', '-c', 'echo "Hello, Kubernetes!" && sleep 5' ]
